# MONGO - PEDIDOS
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-pedidos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-pedidos
  template:
    metadata:
      labels:
        app: mongo-pedidos
    spec:
      containers:
        - name: mongo-pedidos
          image: mongo:6.0
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: example

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-pedidos-service
spec:
  selector:
    app: mongo-pedidos
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP

# MONGO - PAGAMENTOS
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-pagamentos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-pagamentos
  template:
    metadata:
      labels:
        app: mongo-pagamentos
    spec:
      containers:
        - name: mongo-pagamentos
          image: mongo:6.0
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: example

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-pagamentos-service
spec:
  selector:
    app: mongo-pagamentos
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP

# MONGO - PRODUCAO
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-producao
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-producao
  template:
    metadata:
      labels:
        app: mongo-producao
    spec:
      containers:
        - name: mongo-producao
          image: mongo:6.0
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: example

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-producao-service
spec:
  selector:
    app: mongo-producao
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP
