# MICRO SERVIÇO PAGAMENTOS
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: servicopagamentos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: servicopagamentos
  template:
    metadata:
      labels:
        app: servicopagamentos
    spec:
      containers:
      - name: servicopagamentos
        image: 100527548163.dkr.ecr.us-east-1.amazonaws.com/servicopagamentos-repo:latest
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_URLS
          value: http://*:8080
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
---
apiVersion: v1
kind: Service
metadata:
  name: servicopagamentos
spec:
  type: LoadBalancer
  selector:
     app: servicopagamentos
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080