# MICRO SERVIÇO PEDIDOS
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: servicopedidos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: servicopedidos
  template:
    metadata:
      labels:
        app: servicopedidos
    spec:
      containers:
      - name: servicopedidos
        image: 100527548163.dkr.ecr.us-east-1.amazonaws.com/servicopedidos-repo:latest
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_URLS
          value: http://*:8080
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
---
apiVersion: v1
kind: Service
metadata:
  name: servicopedidos
spec:
  type: LoadBalancer
  selector:
     app: servicopedidos
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080